# Variables for ingame-text: %name%,%world-name%,%players%,%gamemode%,%ip-address%,%item-in-hand% !
# Variables for system-motds: Special characters like: hearts,check,star,bar,arrow,pencil: http://dev.bukkit.org/bukkit-plugins/ingamemotd/pages/special-characters/
# If random: true, the system-motds will be shown randomly !
# If joinANDquitMSG: true, the "JoinMSG" & "QuitMSG" will work, if "false" will not work.
# Here are the 2 of the MOTDS, ingame and system !
InGameMotdActive: true
SystemMotdActive: true
motd:
  ingame-text: '&9Welcome to the -newline-&4server&f! '
  system-motds:
  - '&5DEFAULT&f-&cMOTD -newline-&9EXAMPLE:&21'
  - '&5DEFAULT&f-&cMOTD -newline-&9EXAMPLE:&22'
  - '&5DEFAULT&f-&cMOTD -newline-&9EXAMPLE:&23'
  - '&5DEFAULT&f-&cMOTD -newline-&9EXAMPLE:&24'
  - '&5DEFAULT&f-&cMOTD -newline-&9EXAMPLE:&25'
  random: false
messages:
  Prefix: '&e[&2&lMOTD&e]&f '
  NoPermission: '&4You dont have permission to do this!'
  SpecifyMessage: '&7Please specify a message!'
  ReloadConfig: '&bConfig has been reloaded!'
  ConfigReset: '&bConfig has been reset!'
  IngameSET: '&dIN-GAME MOTD set to: '
  joinANDquitMSG: false
  JoinMSG: '&e-name- has joined the game.'
  QuitMSG: '&e-name- has quit the game.'
Version: 1
